### ISSUE TITLE
paragraph 타입 style의 text_align 프로퍼티는 안쓰이나요?

### ISSUE THREAD

**Issue by algoshipda** [riiicruitwww/render-passage-algoshipda#2]
@vchoisk 

안녕하세요

paragraph 타입 style의 text_align 프로퍼티가 있는데요.
올라와 있는 이미지를 봤을 때는 저 프로퍼티와 관련없이 왼쪽 정렬이 되고 있는거 같은데,
안쓰이는 프로퍼티인가요?

**Comment by vchoisk** [comment]
@algoshipda 

네 웹에서는 해당 프로퍼티는 사용되지 않고있습니다. 
그외의 font-size, offset등의 스타일 관련 값도 마찬가지 입니다.

FYI: 해당 데이터의 경우 IOS와 android에서도 동일하게 사용되기 때문에 타 플렛폼에 종속된 데이터가 같이 내려오고 있습니다.

**Comment by algoshipda** [comment]
감사합니다
